# Site settings
title: jsfest.berlin – Berlin, September 2014
description: "jsfest.berlin is a collection of fine events around the web, happening in Berlin in September 2014"
baseurl: ""
url: "http://jsfest.berlin"
exclude:
  - README.md

# Build settings
markdown: kramdown
permalink: pretty
