# Site settings
title: jsfest.berlin – Berlin, September 2014
email: 
description: "jsfest.berlin is a collection of fine events around the web, happening in Berlin in September 2014"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: 
github_username: 

# Build settings
markdown: kramdown
permalink: pretty
