# Site settings
title: jsfest.berlin
email: mail@kevinlorenz.com
description: "jsfest.berlin"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: verpixelt
github_username:  verpixelt

# Build settings
markdown: kramdown
permalink: pretty
