# Site settings
title: jsfest.berlin
email: 
description: "jsfest.berlin"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: 
github_username: 

# Build settings
markdown: kramdown
permalink: pretty
